# Bibliotecas

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Primeira olhada no DF

In [ ]:
df = pd.read_csv('C:\Arquivos Vsco\Projeto Serenatto\data\serenatto_2sem_2023.csv')
df.head()

<>:1: SyntaxWarning: "\A" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\A"? A raw string is also an option.
<>:1: SyntaxWarning: "\A" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\A"? A raw string is also an option.
C:\Users\user\AppData\Local\Temp\ipykernel_8348\2251040531.py:1: SyntaxWarning: "\A" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\A"? A raw string is also an option.
  df = pd.read_csv('C:\Arquivos Vsco\Projeto Serenatto\data\serenatto_2sem_2023.csv')

     id        data           produto  valor   metodo_pagamento
0  2720  2023-07-01  Risoto de Funghi   13.0   Cartão de Débito
1  2721  2023-07-02          Tiramisù   10.0   Cartão de Débito
2  2722  2023-07-02          Tiramisù   10.0  Cartão de Crédito
3  2723  2023-07-02       Ratatouille    8.5                PIX
4  2724  2023-07-03       Ratatouille    8.5           Dinheiro

In [ ]:
df.describe()

                id       valor
count   856.000000  856.000000
mean   3147.500000    7.619159
std     247.250211    3.174247
min    2720.000000    2.500000
25%    2933.750000    4.500000
50%    3147.500000    8.000000
75%    3361.250000   10.500000
max    3575.000000   13.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 856 entries, 0 to 855
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                856 non-null    int64
 1   data              856 non-null    object
 2   produto           856 non-null    object
 3   valor             856 non-null    float64
 4   metodo_pagamento  856 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 33.6+ KB

A coluna de data não está classificada como data, isso talvez possa prejudicar futuras análises

In [ ]:
df.isnull().sum()

id                  0
data                0
produto             0
valor               0
metodo_pagamento    0
dtype: int64

Não há nenhum valor nulo